"""Add feature_vector to LostItem and LostReport

Revision ID: d605508a9ef9
Revises: 
Create Date: 2025-06-10 10:23:22.220002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd605508a9ef9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('feature_vector', sa.JSON(), nullable=True))
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
        batch_op.alter_column('detection_results',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('lost_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('feature_vector', sa.JSON(), nullable=True))
        batch_op.alter_column('item_description',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('lost_date',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('detection_results',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               existing_nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('lost_report', schema=None) as batch_op:
        batch_op.alter_column('detection_results',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('lost_date',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('item_description',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.drop_column('feature_vector')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('lost_item', schema=None) as batch_op:
        batch_op.alter_column('detection_results',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.drop_column('feature_vector')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
